// I2S Microphone Settings

// Which channel is the I2S microphone on? I2S_CHANNEL_FMT_ONLY_LEFT or I2S_CHANNEL_FMT_ONLY_RIGHT
#define I2S_MIC_CHANNEL I2S_CHANNEL_FMT_ONLY_LEFT
// #define I2S_MIC_CHANNEL I2S_CHANNEL_FMT_ONLY_RIGHT
#define I2S_MIC_SERIAL_CLOCK GPIO_NUM_27
#define I2S_MIC_LEFT_RIGHT_CLOCK GPIO_NUM_12
#define I2S_MIC_SERIAL_DATA GPIO_NUM_14

// Define external DAC Pins
#define I2S_EDAC_WS GPIO_NUM_4
#define I2S_EDAC_BCK GPIO_NUM_0
#define I2S_EDAC_DATA GPIO_NUM_2

//Activation Button Pins
#define ASSISTANT_ACTIVATION_BUTTON_PIN GPIO_NUM_23
#define EXT_ACTIVATION_BUTTON_PIN GPIO_NUM_13

