runtime: python37

# [START handlers]
handlers:
- url: /static
  static_dir: static
  secure: always
- url: /.*
  script: auto
  secure: always
# [END handlers]

#[START env]
env_variables:
    CLOUD_STORAGE_BUCKET: samplecollection_project_friday
    SESSION_SECRET_KEY: P/1sqJcubmeNGG1vtwlJq6LYiaTCwbHeRzZpyGMs
#[END env]
